services:
  #  onspot-app:
  #    build: .
  #    container_name: onspot-app
  #    ports:
  #      - "8080:8080"
  #    restart: unless-stopped
  #    depends_on:
  #      - postgres
  #      - minio
  #    environment:
  #      SPRING_APPLICATION_NAME: flood-aid
  #      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/flood_aid_db
  #      SPRING_DATASOURCE_USERNAME: root
  #      SPRING_DATASOURCE_PASSWORD: secret
  #      SPRING_JPA_HIBERNATE_DDL_AUTO: update
  #      SPRING_JPA_SHOW_SQL: true
  #      MINIO_URL: http://minio:9001
  #      MINIO_ACCESS_NAME: minioadmin
  #      MINIO_ACCESS_SECRET: miniopassword
  #      SERVER_TOMCAT_RELAXED_QUERY_CHARS: "|,{,},[,]"
  #      LINE_CHANNEL_ID: 2006662146
  #    networks:
  #      - flood_aid_net

  postgres:
    image: postgres:latest
    container_name: flood_aid_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./src/main/java/com/example/flood_aid/db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/main/java/com/example/flood_aid/db/migrations/mock_data.sql:/docker-entrypoint-initdb.d/mock_data.sql
      - ./src/main/java/com/example/flood_aid/db/migrations/thai_location.sql:/docker-entrypoint-initdb.d/thai_location.sql
    networks:
      - flood_aid_net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: flood_aid_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin # This volume will persist pgAdmin data
    networks:
      - flood_aid_net

volumes:

  postgres_data:
  pgadmin_data:


networks:
  flood_aid_net:
    driver: bridge
