apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onspot-ingress
  namespace: onspot
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - onspot-app.kingsglaive.me
        - minio-console.kingsglaive.me
        - minio-api.kingsglaive.me
        - pgadmin.kingsglaive.me
      secretName: onspot-tls
  rules:
    - host: onspot-app.kingsglaive.me
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: onspot-service
                port:
                  number: 8080
    - host: minio-api.kingsglaive.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9000
    - host: minio-console.kingsglaive.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9001
    - host: pgadmin.kingsglaive.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pgadmin
                port:
                  number: 8888
